# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Samuel Oliveira
email: your-email@domain.com
description: Desenvolvedor Front-End em construção e apaixonado por novos conhecimentos.
about: Samuel Hendrix Dantas de Oliveira, 18 anos, cursando Análise e Desenvolvimento de sistemas no Instituto Federal do Rio Grande do Norte. Apaixonado por tecnologia e por novos conhecimentos, como também, entrando no mundo front-end com o objetivo de atuar de forma profissional. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /:year/:title
